package com.shawn.dev;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * A utilization class to construct regular expressions <br>
 * e.g SmoothExpression.regex().startOfLine().anythingBut(" ").endOfLine().build()
 *
 * @author Qijun
 * @since v1.0
 */
public class SmoothExpression {

    /**
     * A constructor to construct SmoothExpression object from normal Java Patterns
     *
     * @param pattern the pattern to built from
     */
    public SmoothExpression(final Pattern pattern) {
        this.pattern = pattern;
    }

    /**
     * Get the regular expression which is generated by SmoothExpression
     *
     * @return the actual regular expression that is built
     */
    public String getRegularExpression() {
        return this.pattern.pattern();
    }

    /**
     * check if target matches the specified expression
     *
     * @param target the target string to check
     * @return true for match and false for not
     */
    public boolean matches(String target) {
        return pattern.matcher(target).matches();
    }

    /**
     * Find all pieces that match specified pattern and capturing group
     *
     * @param target the String to find matches from
     * @param group the index of capturing groups, 0 for entire pattern and (1,..) for corresponding groups
     * @return a list of matches
     */
    public List<String> findGroups(final String target, final int group) {
        List<String> groups = new ArrayList<String>();
        Matcher m = pattern.matcher(target);
        while (m.find()) {
            groups.add(m.group(group));
        }
        return groups;
    }

    /**
     * Internal standard Java Pattern object for matching and capturing
     */
    private final Pattern pattern;

    /**
     * start an actual builder to build the expression<br>
     * e.g Expression.regex().startOfLine().then("hello world").endOfLine().build()
     *
     * @return a ExpressionBuilder object to build the SmoothExpression itself
     */
    public static ExpressionBuilder regex() {
        return new ExpressionBuilder();
    }

    /**
     * An static inner class which is used to build the SmoothExpression
     */
    public static class ExpressionBuilder {
        private StringBuilder prefix = new StringBuilder();
        private StringBuilder patternContent = new StringBuilder();
        private StringBuilder suffix = new StringBuilder();
        private int modifiers = Pattern.MULTILINE;

        /**
         * protected constructor that can only
         * be called inside the package scope
         */
        ExpressionBuilder() {

        }

        /**
         * A private quick method to add a piece of pattern that should
         * not be captured in the group capturing, the added pattern with
         * be wrapped with (?: )
         *
         * @param content the content of the piece of pattern
         * @return the builder
         */
        private ExpressionBuilder add(String content) {
            patternContent.append("(?:" + content + ")");
            return this;
        }

        /**
         * Matches any character, visible or not
         *
         * @return the builder
         */
        public ExpressionBuilder anyChar() {
            this.add("[\\s\\S]");
            return this;
        }

        /**
         * Matches any character except specified characters
         *
         * @param content the string of characters which shouldn't be matched
         * @return the builder
         */
        public ExpressionBuilder anyCharBut(String content) {
            this.add("[^" +  content + "]");
            return this;
        }

        /**
         * Matches anything of any length
         *
         * @return the builder
         */
        public ExpressionBuilder anything() {
            this.add("[\\s\\S]*");
            return this;
        }

        /**
         * Matches anything of any length except specified characters
         *
         * @param content the string of characters which shouldn't be matched
         * @return the builder
         */
        public ExpressionBuilder anythingBut(String content) {
            this.add("[^" +  content + "]*");
            return this;
        }

        /**
         * Declare a start of line mark.<br>
         * e.g SmoothExpression.regex().startOfLine()... will generate a regular expression of "^..."<br>
         * Attention: {@link #startOfLine()} only works when it is applied as the first element and will cause
         * unexpected results otherwise.
         *
         * @return the builder
         */
        public ExpressionBuilder startOfLine() {
            this.add("^");
            return this;
        }

        /**
         * Declare a end of line mark.<br>
         * e.g SmoothExpression.regex()...endOfLine().build() will generate a regular expression of "...$"<br>
         * Attention: {@link #endOfLine()} only works when it is applied as the last element and will cause
         * unexpected results otherwise.
         *
         * @return the builder
         */
        public ExpressionBuilder endOfLine() {
            this.add("$");
            return this;
        }

        /**
         * Matches a single digit from 0 to 9
         *
         * @return the builder
         */
        public ExpressionBuilder singleDigit() {
            this.add("\\d");
            return this;
        }

        /**
         * Matches an entire non-negative integer number, e.g. 0, 111, 1121..
         * will not match a negative integer
         *
         * @return the builder
         */
        public ExpressionBuilder nonNegativeInteger() {
            this.add("\\d+");
            return this;
        }

        /**
         * Matches an entire negative integer number, e.g. -1., -2321..
         * will not match a zero or any positive integers
         *
         * @return the builder
         */
        public ExpressionBuilder negativeInteger() {
            this.add("-\\d+");
            return this;
        }

        /**
         * Matches an invisible character, e.g \n \t...
         *
         * @return the builder
         */
        public ExpressionBuilder space() {
            this.add("\\s");
            return this;
        }

        public ExpressionBuilder nonSpace() {
            this.add("\\S");
            return this;
        }

        public ExpressionBuilder anyOf(final String content) {
            patternContent.append("[" + content + "]");
            return this;
        }

        public ExpressionBuilder floatNumber() {
            this.add("-?([1-9]\\d*\\.\\d*|0\\.\\d*[1-9]\\d*|0?\\.0+|0)");
            return this;
        }

        public ExpressionBuilder wordChar() {
            this.add("[a-zA-Z]");
            return this;
        }

        public ExpressionBuilder nonWordChar() {
            this.add("[^a-zA-z]");
            return this;
        }

        public ExpressionBuilder find(final String content) {
            this.patternContent.append("(" + content + ")");
            return this;
        }

        public ExpressionBuilder then(final String content) {
            this.add(content);
            return this;
        }

        public ExpressionBuilder capture() {
            patternContent.append("(");
            return this;
        }

        public ExpressionBuilder endCapture() {
            patternContent.append(")");
            return this;
        }

        public ExpressionBuilder oneOrMore() {
            this.add("+");
            return this;
        }

        public ExpressionBuilder zeroOrMore() {
            this.add("*");
            return this;
        }

        public ExpressionBuilder maybe(final String content) {
            patternContent.append("(?:" + content + ")?");
            return this;
        }

        public ExpressionBuilder oneOf(final String... contents) {
            this.add(String.join("|", contents));
            return this;
        }

        /**
         * Append a pattern of multiple times to the pattern in construction.
         * Minimum and maximum number of replications can be set to null for no such demands
         *
         * @param content the pattern itself
         * @param min minimum time that the pattern should appear
         * @param max maximum time that the pattern should appear
         * @return the builder
         */
        public ExpressionBuilder multiple(final String content, Integer min, Integer max) {
            if (min == null && max == null) {
                this.patternContent.append("(?:" + content + ")+");
                return this;
            } else if (min == null && max != null) {
                this.patternContent.append("(?:" + content + "){1," + max + "}");
                return this;
            } else if (min != null && max == null) {
                this.patternContent.append("(?:" + content + "){" + min + ",}");
                return this;
            } else if (min != null && max != null) {
                this.patternContent.append("(?:" + content + "){" + min + "," + max + "}");
                return this;
            }
            return this;
        }

        /**
         * Add modifiers to SmoothExpression.
         *
         * @param modifier the usual modifier of Java Pattern modifiers to add
         * @return the builder
         */
        public ExpressionBuilder addModifier(final char modifier) {
            switch (modifier) {
                case 'd':
                    modifiers |= Pattern.UNIX_LINES;
                    break;
                case 'i':
                    modifiers |= Pattern.CASE_INSENSITIVE;
                    break;
                case 'x':
                    modifiers |= Pattern.COMMENTS;
                    break;
                case 'm':
                    modifiers |= Pattern.MULTILINE;
                    break;
                case 's':
                    modifiers |= Pattern.DOTALL;
                    break;
                case 'u':
                    modifiers |= Pattern.UNICODE_CASE;
                    break;
                case 'U':
                    modifiers |= Pattern.UNICODE_CHARACTER_CLASS;
                    break;
                default:
                    break;
            }

            return this;
        }

        /**
         * Remove modifiers from SmoothExpression.
         *
         * @param modifier the usual modifier of Java Pattern modifiers to remove
         * @return the builder
         */
        public ExpressionBuilder removeModifier(final char modifier) {
            switch (modifier) {
                case 'd':
                    modifiers &= ~Pattern.UNIX_LINES;
                    break;
                case 'i':
                    modifiers &= ~Pattern.CASE_INSENSITIVE;
                    break;
                case 'x':
                    modifiers &= ~Pattern.COMMENTS;
                    break;
                case 'm':
                    modifiers &= ~Pattern.MULTILINE;
                    break;
                case 's':
                    modifiers &= ~Pattern.DOTALL;
                    break;
                case 'u':
                    modifiers &= ~Pattern.UNICODE_CASE;
                    break;
                case 'U':
                    modifiers &= ~Pattern.UNICODE_CHARACTER_CLASS;
                    break;
                default:
                    break;
            }

            return this;
        }

        /**
         * build the SmoothExpression that can be used for matching and grouping
         *
         * @return the built SmoothExpression object
         */
        public SmoothExpression build() {
            Pattern pattern = Pattern.compile(
                    this.prefix.toString() +
                    this.patternContent.toString() +
                    this.suffix.toString(),
                    modifiers);
            return new SmoothExpression(pattern);
        }

    }

    /**
     * main function for test only
     *
     * @param args no use
     */
    public static void main(String[] args) {
        SmoothExpression exp = SmoothExpression.regex().nonNegativeInteger().build();
        System.out.println(exp.getRegularExpression());
        System.out.println(exp.matches("-111"));
        List<String> list = exp.findGroups("11aa12aa", 0);
        for (String s : list) {
            System.out.println(s);
        }
    }

}